### ISSUE TITLE
iptables-nf rules is not working for the POD traffic

### ISSUE THREAD

**Issue by psaini79** [ovn-kubernetes/ovn-kubernetes#5161]
### What would you like to know?

We are testing our application in openshift pod and OVN is the default network CNI. We are trying to restrict some traffic from pod to certain nodes. We added the rules in iptables-nf for testing purpose to block the connection if it is destined to a certain pod.

We have a pod scheduled on compute node1 and added following rule:
```
iptables-nf -t raw -I PREROUTING 1 tcp --dport 9090 -j DROP
iptables -A OUTPUT -d 172.0.1.105 -p icmp -j DROP
```

When we start the ping from the pod to 172.0.1.105, it goes fine. I am wondering how we can manage the traffic from pod to outside. The above are just example, we need to restrict traffic or perform some actions based on TCP flags.

We openshfit 4.18.1  and Redhat 8.10 on worker node. I used ovn-trace utility but it didn't help me much and provide following output:

`ovn-detrace pod to external IP indicates success from ocpod1 to 172.0.1.105`

I also tried to set the egress firewall but it is not meeting the requirement as I want to add tcpflags such as FIN and RST in following:

```
# cat egress_firewalld.txt
---
kind: EgressFirewall
apiVersion: k8s.ovn.org/v1
metadata:
  name: default
  namespace: default
spec:
  egress:
  - type: Deny
    to:
     cidrSelector: 0.0.0.0/0
    ports:
    - port: 9090
      protocol: TCP
```
